### ISSUE TITLE
please improve error reporting

### ISSUE THREAD

**Issue by verymilan** [diggers-mt/minetest-matrix#10]
Hi there, an quite unclear error happened:

```
ServerError: AsyncErr: environment_Step: Runtime error from matrix/lua-matrix/matrix/client.lua:344: HTTP 0 - unknown error
 stack traceback:
       [C]: in function 'login'
matrix/lua-matrix/matrix/client.lua:344: in function 'login_with_password'
matrix/init.lua:125: in function 'connect'
matrix/init.lua:106: in function <matrix/init.lua:104>
game/register.lua:412: in function <game/register.lua:392>
```

If possible, please improve the error feedback so we know what exactly went wrong...

**Comment by joenas** [comment]
Well the error occurs in https://github.com/aperezdc/lua-matrix and not the mod per se but I'll see if it's something we can catch. 
Would be nice with some more context, like what kind of setup you have, how it's configured etc so I can reproduce.

**Comment by joenas** [comment]
A quick guess would be that the synapse (or whatever matrix server you're running) isn't accessible. Could be port configuration, bad SSL cert or something in the likes of that.

**Comment by joenas** [comment]
I've added a few checks to the HS url. Please try with recent `master` and note that you must remove the `matrix.port` setting as its useless.

**Comment by joenas** [comment]
Also remember to do `git submodule update --remote --merge` to fetch the new submodule

**Comment by joenas** [comment]
Any chance to try this out? If working please close the issue.
