### ISSUE TITLE
Implement set_display_name

### ISSUE THREAD

**Issue by tacotexmex** [diggers-mt/minetest-matrix#2]
Display names can be set [like this](https://github.com/aperezdc/lua-matrix/blob/master/examples/set-display-name.lua). There can be a global settings variable called `matrix.display_name` defining it.

**Comment by joenas** [comment]
You need to register a user beforehand anyway so not really worth it IMHO

**Comment by tacotexmex** [comment]
Fine! ¯\_(ツ)_/¯
