### ISSUE TITLE
Remove need for secure.enable_security = true

### ISSUE THREAD

**Issue by joenas** [diggers-mt/minetest-matrix#6]
Either fix what's needed for `secure.trusted_mods` to work or implement without external requirements. 

For the latter, there is http://dev.minetest.net/minetest.request_http_api() and http://dev.minetest.net/minetest.request_http_api()

**Comment by joenas** [comment]
https://github.com/diggers-mt/minetest-matrix/tree/request_insecure_environment fixes using only `secure.trusted_mods`. IMHO it's **too much work** to implement this functionality without external deps..

**Comment by tacotexmex** [comment]
Yes, a new lib would be needed. Only needing to put the mod as trusted is good enough for now, and on par with what irc mod demands.
